import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { createArtifact } from './artifacts.js';

const $=s=>document.querySelector(s),PI=Math.PI;
const palette=[0xe6ad64,0xd84242,0xb54986,0x7455b6,0x536fa9];
const vertex=`attribute float aSize;attribute vec3 aColor;attribute float aPhase;varying vec3 vColor;varying float vAlpha;
uniform float uTime;uniform float uRatio;uniform float uReveal;uniform vec3 uGravity;uniform float uPull;uniform float uWave;uniform float uWarp;uniform float uDim;
void main(){vec3 p=position;float r=length(p.xz);float a=uTime*.009*(1.+6./(r+2.));float c=cos(a),s=sin(a);p.xz=mat2(c,-s,s,c)*p.xz;
 p.y+=sin(uTime*.14+aPhase+r*.15)*.09;vec3 d=uGravity-p;float dis=length(d);p+=d*uPull*exp(-dis*.085)*.18;
 float ring=exp(-pow((r-uWave)*.7,2.));p.y+=ring*sin(aPhase)*1.6;p.xz*=1.+ring*.025;
 p*=.15+.85*uReveal;p.z+=uWarp*sin(aPhase)*1.6;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;
 gl_PointSize=clamp(aSize*uRatio*260./max(1.,-mv.z),.6,8.5);vColor=aColor*(1.+ring*.9);vAlpha=(.4+.6*sin(aPhase+uTime*.13)*sin(aPhase+uTime*.13))*uDim;}`;
const fragment=`varying vec3 vColor;varying float vAlpha;void main(){vec2 p=gl_PointCoord*2.-1.;float r=dot(p,p);if(r>1.)discard;float a=exp(-r*5.5)*vAlpha;gl_FragColor=vec4(vColor,a);}`;
const hazeVertex=`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const hazeFragment=`varying vec2 vUv;uniform float uTime;uniform float uDim;uniform float uReveal;uniform float uWarp;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
void main(){vec2 p=(vUv-.5)*2.;float r=length(p);float a=atan(p.y,p.x);float arm=pow(.5+.5*cos(a*4.-r*15.+uTime*.013),3.);float n=noise(p*12.+uTime*.015)+.4*noise(p*29.);float mask=smoothstep(1.,.35,r)*smoothstep(.01,.11,r);vec3 color=mix(vec3(.18,.065,.045),vec3(.07,.045,.15),r);gl_FragColor=vec4(color,(arm*.18+n*.025)*mask*uDim*uReveal);}`;
function rng(seed){let n=seed|0;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;}
function smooth(t){return 1-Math.pow(1-t,3);}
function makeGlowTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d');const g=c.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,226,176,1)');g.addColorStop(.08,'rgba(255,180,88,.8)');g.addColorStop(.23,'rgba(229,95,42,.23)');g.addColorStop(.56,'rgba(111,50,61,.05)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,128,128);return new THREE.CanvasTexture(canvas);}
function freeGroup(group){const gs=new Set(),ms=new Set();group.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>ms.add(m));});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());group.clear();}
function galaxyCloud(count,radius,random,uniforms){
 const positions=new Float32Array(count*3),colors=new Float32Array(count*3),sizes=new Float32Array(count),phases=new Float32Array(count);
 for(let i=0;i<count;i++){const r=Math.pow(random(),.82)*radius+.18,branch=i%4;const fuzz=(random()+random()+random()-1.5);const theta=branch*PI*.5+r*.24+fuzz*(.05+r*.02);positions[i*3]=Math.cos(theta)*r;positions[i*3+2]=Math.sin(theta)*r;positions[i*3+1]=(random()+random()-1)*(.11+r*.034);const index=Math.min(4,Math.floor(r/radius*4.6));const color=new THREE.Color(palette[index]).multiplyScalar(.68+random()*.8);colors.set([color.r,color.g,color.b],i*3);sizes[i]=.35+Math.pow(random(),6)*1.8;phases[i]=random()*PI*2;}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('aColor',new THREE.BufferAttribute(colors,3));geometry.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));geometry.setAttribute('aPhase',new THREE.BufferAttribute(phases,1));
 const material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false});const points=new THREE.Points(geometry,material);points.frustumCulled=false;return points;
}
export function initUniverse(options){
 const {catalog,seed=71,visited=new Set(),onNavigate,onSelect,onHover,onReady,onIntroFinished}=options;
 const canvas=$('#universe-canvas'),mobile=()=>innerWidth<700,reduced=matchMedia('(prefers-reduced-motion:reduce)'),random=rng(seed);
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});
 renderer.setClearColor(0x060609,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.68;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile()?1.25:1.5));
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.08,1000);
 const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.065;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=220;controls.autoRotate=false;controls.rotateSpeed=.5;controls.zoomSpeed=.7;controls.enabled=false;
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const environment=pmrem.fromScene(room,.035);scene.environment=environment.texture;room.dispose();pmrem.dispose();scene.environmentIntensity=.72;
 scene.add(new THREE.AmbientLight(0x857691,1.4));const key=new THREE.DirectionalLight(0xffd9a4,3.5);key.position.set(14,18,9);scene.add(key);const rim=new THREE.DirectionalLight(0x8b71cf,2.7);rim.position.set(-12,4,-8);scene.add(rim);const red=new THREE.PointLight(0xe96c56,65,80,2);red.position.set(-7,6,13);scene.add(red);
 const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.28,.32,.88);composer.addPass(bloom);composer.addPass(new OutputPass());
 const globalUniforms={uTime:{value:0},uRatio:{value:renderer.getPixelRatio()},uReveal:{value:.05},uGravity:{value:new THREE.Vector3()},uPull:{value:0},uWave:{value:-30},uWarp:{value:0},uDim:{value:1}};
 const cosmos=new THREE.Group();cosmos.rotation.y=.14;scene.add(cosmos);const cloud=galaxyCloud(mobile()?40000:82000,29,random,globalUniforms);cosmos.add(cloud);
 const haze=new THREE.Mesh(new THREE.PlaneGeometry(64,64),new THREE.ShaderMaterial({vertexShader:hazeVertex,fragmentShader:hazeFragment,uniforms:globalUniforms,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false,side:THREE.DoubleSide}));haze.rotation.x=-PI/2;haze.position.y=-.5;cosmos.add(haze);
 const bgGeometry=new THREE.BufferGeometry(),bgPositions=new Float32Array(6500*3),bgColors=new Float32Array(6500*3);
 for(let i=0;i<6500;i++){const theta=random()*PI*2,phi=Math.acos(2*random()-1),r=120+random()*180;bgPositions.set([r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta)],i*3);const c=new THREE.Color(palette[i%5]).multiplyScalar(.1+random()*.38);bgColors.set([c.r,c.g,c.b],i*3);}
 bgGeometry.setAttribute('position',new THREE.BufferAttribute(bgPositions,3));bgGeometry.setAttribute('color',new THREE.BufferAttribute(bgColors,3));const background=new THREE.Points(bgGeometry,new THREE.PointsMaterial({size:.16,vertexColors:true,transparent:true,opacity:.7,depthWrite:false}));scene.add(background);
 const glowTexture=makeGlowTexture(),core=new THREE.Group();const coreBall=new THREE.Mesh(new THREE.SphereGeometry(.88,48,32),new THREE.MeshBasicMaterial({color:0x08050a}));core.add(coreBall);
 for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.24+i*.18,.015,5,128),new THREE.MeshBasicMaterial({color:i?0xb66145:0xe4ac5e,transparent:true,opacity:.68-i*.12}));ring.rotation.x=PI/2+.15;ring.rotation.y=.22;core.add(ring);}
 const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:0xedab73,transparent:true,opacity:.2,blending:THREE.AdditiveBlending,depthWrite:false}));glow.scale.set(7,7,1);core.add(glow);cosmos.add(core);
 const galaxies=new Map(),sectors=new Map(),planets=new Map();
 for(const g of catalog.galaxies){galaxies.set(g.id,{...g,type:'galaxy',theme:g.theme});for(const s of g.sectors){sectors.set(s.id,{...s,type:'sector',galaxyId:g.id,theme:g.theme});for(const p of s.planets)planets.set(p.id,{...p,type:'planet',galaxyId:g.id,sectorId:s.id,theme:g.theme});}}
 let level=null,selected=null,transition=null,frame=0,previous=0,elapsedTime=0,introStart=null,introDone=false,disposed=false,hovered=null,hold=null,pointerStart=null,clickTimer=0,tourTimer=0,touring=false,audio=null,audioOn=false;
 let waveAge=99,pullTarget=0,particleRate=1,hiddenAt=0;const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),projected=new THREE.Vector3(),pullPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0),events=[];
 const meteors=[];const pathTo=id=>{if(id==='home'||!id)return[];const g=galaxies.get(id),s=sectors.get(id),p=planets.get(id);if(g)return[{id:g.id,name:g.name,type:'galaxy'}];if(s)return[{id:s.galaxyId,name:galaxies.get(s.galaxyId).name,type:'galaxy'},{id:s.id,name:s.name,type:'sector'}];if(p)return[{id:p.galaxyId,name:galaxies.get(p.galaxyId).name,type:'galaxy'},{id:p.sectorId,name:sectors.get(p.sectorId).name,type:'sector'},{id:p.id,name:p.name,type:'planet'}];return null;};
 const on=(target,type,fn,opts)=>{target.addEventListener(type,fn,opts);events.push(()=>target.removeEventListener(type,fn,opts));};
 function starModel(node,index,depth){const group=new THREE.Group(),color=new THREE.Color(node.color||palette[(index+depth)%5]);const ball=new THREE.Mesh(new THREE.SphereGeometry(depth? .32:.23,32,24),new THREE.MeshBasicMaterial({color:color.clone().multiplyScalar(1.3)}));group.add(ball);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color,transparent:true,opacity:depth?.6:.47,blending:THREE.AdditiveBlending,depthWrite:false}));halo.scale.set(depth?5:3.3,depth?5:3.3,1);group.add(halo);for(let j=0;j<(depth?3:1);j++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.75+j*.31,.008,3,90),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.16}));ring.rotation.set(PI/2+.15+j*.18,.16*j,.12);group.add(ring);}return{group,update:(dt,t)=>{halo.material.opacity=(depth?.54:.42)+Math.sin(t*.6+index)*.04;group.rotation.y+=dt*.025;},setParameter(){},pulse(){halo.material.opacity=.8;},dispose(){freeGroup(group);}};}
 function nodePosition(index,count,depth){if(depth===0){const a=index/count*PI*2+.35,r=17+Math.sin(index*2.3)*2;return new THREE.Vector3(Math.cos(a)*r,Math.sin(index*1.9)*.75,Math.sin(a)*r*.75);}return new THREE.Vector3((index?1:-1)*(depth===1?9:6.4),index?-.1:.6,index?-1.2:1.2);}
 function pose(depth,planetNode=null){const fit=Math.max(1,.91/(innerWidth/innerHeight));if(planetNode){const target=planetNode.position.clone().add(new THREE.Vector3(mobile()?0:4.5,mobile()?-3.2:0,0));return{target,position:target.clone().add(new THREE.Vector3(5.4,4.6,20.5).multiplyScalar(mobile()?1.07:1))};}return{target:new THREE.Vector3(0,0,0),position:new THREE.Vector3(0,depth===0?32:depth===1?20:10,depth===0?59:depth===1?35:30).multiplyScalar(fit)};}
 function disposeLevel(){if(!level)return;for(const n of level.nodes)n.artifact.dispose();for(const cloud of level.clouds){cloud.geometry.dispose();cloud.material.dispose();}for(const ring of level.rings){ring.geometry.dispose();ring.material.dispose();}scene.remove(level.group);level.group.clear();level=null;$('#star-labels').innerHTML='';}
 function buildLevel(path){
  disposeLevel();selected=null;core.visible=true;const depth=Math.min(path.length,2),parent=depth===0?null:depth===1?galaxies.get(path[0].id):sectors.get(path[1].id);const entries=depth===0?[...galaxies.values()]:depth===1?parent.sectors.map(s=>sectors.get(s.id)):parent.planets.map(p=>planets.get(p.id));
  const group=new THREE.Group();scene.add(group);level={group,nodes:[],clouds:[],rings:[],depth,path:path.slice(0,depth),id:parent?.id||'home'};
  for(let i=0;i<entries.length;i++){
   const entry=entries[i],artifact=depth===2?createArtifact(entry,{quality:mobile()?.75:1}):starModel(entry,i,depth);const position=nodePosition(i,entries.length,depth);artifact.group.position.copy(position);artifact.group.traverse(o=>{o.userData.coordinate=entry.id;});group.add(artifact.group);
   const button=document.createElement('button');button.className='star-label'+(depth===2?' planet-label':'');button.dataset.node=entry.id;button.setAttribute('aria-label',(depth===2?'体验':'进入')+entry.name+(depth===1?'子星系':''));button.style.setProperty('--node-color',entry.color||'#d5aa70');const orbit=document.createElement('span');orbit.className='label-orbit';const text=document.createElement('span');const strong=document.createElement('strong');strong.textContent=entry.name;const small=document.createElement('small');small.textContent=depth===0?entry.en:depth===1?'SUBSYSTEM / '+entry.en:entry.en;text.append(strong,small);button.append(orbit,text);$('#star-labels').append(button);button.addEventListener('click',()=>navigateTo(entry.id));button.addEventListener('mouseenter',()=>setHover(entry));button.addEventListener('mouseleave',()=>setHover(null));button.addEventListener('focus',()=>setHover(entry));button.addEventListener('blur',()=>setHover(null));
   level.nodes.push({entry,artifact,position,label:button});
   if(depth===1){const uniforms=Object.fromEntries(Object.entries(globalUniforms).map(([key,value])=>[key,key==='uDim'?{value:.7}:key==='uReveal'?{value:1}:value]));const mini=galaxyCloud(mobile()?7000:14000,5.8,random,uniforms);mini.position.copy(position);mini.rotation.y=i?-.3:.4;group.add(mini);level.clouds.push(mini);}
   if(depth===2){const pts=Array.from({length:129},(_,j)=>{const a=j/128*PI*2;return new THREE.Vector3(position.x+Math.cos(a)*3.7,-1.6,position.z+Math.sin(a)*3.0);});const ring=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xbba174,transparent:true,opacity:.15}));group.add(ring);level.rings.push(ring);}
  }
  refreshLabels();const info={depth,id:level.id,path:level.path,title:depth===0?'万千可能，藏在一片星云。':parent.name,description:depth===0?'选择一颗恒星，进入它的世界。':parent.description};onNavigate?.(info);canvas.dataset.nodeCount=entries.length;canvas.dataset.selection='';canvas.dataset.navigation=transition?'flying':'ready';return level;
 }
 function refreshLabels(){if(!level)return;for(const n of level.nodes){const e=n.entry,seen=e.type==='planet'?visited.has(e.id):[...planets.values()].some(p=>visited.has(p.id)&&(e.type==='galaxy'?p.galaxyId===e.id:p.sectorId===e.id));n.label.classList.toggle('is-visited',seen);}}
 function setHover(node){hovered=node?.id||null;onHover?.(node);for(const n of level?.nodes||[])n.label.classList.toggle('is-hovered',n.entry.id===hovered);canvas.style.cursor=node?'pointer':pullTarget?'grabbing':'grab';}
 function navigateTo(id){
  if(!introDone)return;const path=Array.isArray(id)?id:pathTo(id);if(!path)return;stopTour();clearTimeout(clickTimer);setHover(null);onSelect?.(null);const node=level?.nodes.find(n=>n.entry.id===(typeof id==='string'?id:path.at(-1)?.id));const fromPosition=camera.position.clone(),fromTarget=controls.target.clone();transition={started:performance.now(),duration:reduced.matches?760:1350,path,fromPosition,fromTarget,viaTarget:node?.position.clone()||fromTarget.clone(),built:false,toPose:null};controls.enabled=false;canvas.dataset.navigation='flying';document.body.classList.add('navigating');
 }
 function completeSelection(path){if(path.length<3)return;selected=level.nodes.find(n=>n.entry.id===path[2].id);if(!selected)return;selected.artifact.group.scale.setScalar(mobile()?1.45:2.1);core.visible=false;selected.artifact.pulse('wave');canvas.dataset.selection=selected.entry.id;onNavigate?.({depth:2,id:selected.entry.id,path,planet:true,title:selected.entry.name,description:selected.entry.description});onSelect?.(selected.entry.id);playTone(selected.entry.variant||0);}
 function back(){if(!introDone)return;if(selected)navigateTo(level.path);else if(level?.path.length)navigateTo(level.path.slice(0,-1));else command('wave');}
 function stopTour(){touring=false;clearTimeout(tourTimer);}
 function startTour(){stopTour();touring=true;let index=0;const route=[...galaxies.keys()];const next=()=>{if(!touring)return;const id=route[index++%route.length];navigateTo(id);touring=true;tourTimer=setTimeout(next,8200);};next();}
 function hitAt(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects((level?.nodes||[]).map(n=>n.artifact.group),true);const coordinate=hits.find(h=>h.object.userData.coordinate)?.object.userData.coordinate;return coordinate?level.nodes.find(n=>n.entry.id===coordinate):null;}
 function pullAt(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);raycaster.ray.intersectPlane(pullPlane,globalUniforms.uGravity.value);}
 on(canvas,'pointerdown',e=>{if(!introDone||transition)return;stopTour();pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId,held:false,moved:false};clearTimeout(hold);if(!hitAt(e))hold=setTimeout(()=>{if(!pointerStart||pointerStart.moved)return;pointerStart.held=true;pullTarget=1;controls.enabled=false;pullAt(e);canvas.dataset.gravity='active';},420);});
 on(canvas,'pointermove',e=>{if(!introDone||transition)return;if(pointerStart){const d=Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y);if(d>7&&!pointerStart.held){pointerStart.moved=true;clearTimeout(hold);}if(pointerStart.held)pullAt(e);}else setHover(hitAt(e)?.entry||null);});
 on(window,'pointerup',e=>{clearTimeout(hold);const start=pointerStart;pointerStart=null;pullTarget=0;canvas.dataset.gravity='released';if(!introDone||transition)return;controls.enabled=true;if(e.target!==canvas||!start||start.held||start.moved)return;const node=hitAt(e);clearTimeout(clickTimer);if(node)clickTimer=setTimeout(()=>navigateTo(node.entry.id),210);});
 on(window,'pointercancel',()=>{clearTimeout(hold);pointerStart=null;pullTarget=0;if(introDone&&!transition)controls.enabled=true;});
 on(canvas,'dblclick',e=>{if(!introDone)return;clearTimeout(clickTimer);const node=hitAt(e);if(node)node.artifact.pulse('burst');command('wave');});
 on(canvas,'wheel',()=>{stopTour();}, {passive:true});
 on(canvas,'keydown',e=>{if(!introDone||transition)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();const offset=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')offset.applyAxisAngle(new THREE.Vector3(0,1,0),e.key==='ArrowLeft'?.12:-.12);else if(e.key==='ArrowUp'||e.key==='ArrowDown')offset.y+=e.key==='ArrowUp'?1.2:-1.2;else offset.multiplyScalar(e.key==='+'?.9:1.1);camera.position.copy(controls.target).add(offset);controls.update();}});
 function resize(){renderer.setSize(innerWidth,innerHeight,false);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(introDone&&!transition){const p=pose(level.depth,selected);camera.position.copy(p.position);controls.target.copy(p.target);controls.update();}}
 on(window,'resize',resize);
 on(document,'visibilitychange',()=>{if(document.hidden){hiddenAt=performance.now();audio?.context.suspend();}else{if(hiddenAt&&introStart&&!introDone)introStart+=performance.now()-hiddenAt;hiddenAt=0;if(audioOn)audio?.context.resume();}});
 function meteorShower(){for(let i=0;i<12;i++){const a=i*.7+random();const pts=[new THREE.Vector3(),new THREE.Vector3(-1.5,-.4,2.5)];const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:palette[i%5],transparent:true,opacity:.5}));mesh.position.set((random()-.5)*70,13+random()*20,-30-random()*40);scene.add(mesh);meteors.push({mesh,age:-i*.12,velocity:new THREE.Vector3(14,-4,26),life:2.4});}canvas.dataset.meteors=meteors.length;}
 function wave(){waveAge=0;canvas.dataset.wave=String(Number(canvas.dataset.wave||0)+1);for(const n of level.nodes)n.artifact.pulse('wave');playTone(2);}
 function setupAudio(){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return null;const context=new Context(),gain=context.createGain();gain.gain.value=.025;gain.connect(context.destination);const drones=[55,82.406,110].map((f,i)=>{const osc=context.createOscillator(),g=context.createGain();osc.type=i?'sine':'triangle';osc.frequency.value=f;g.gain.value=.16/(i+1);osc.connect(g);g.connect(gain);osc.start();return osc;});return{context,gain,drones};}
 function playTone(index){if(!audioOn||!audio)return;const osc=audio.context.createOscillator(),g=audio.context.createGain(),now=audio.context.currentTime;osc.type='sine';osc.frequency.value=[220,277.18,329.63,415.3][index%4];g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.06,now+.08);g.gain.exponentialRampToValueAtTime(.001,now+1.5);osc.connect(g);g.connect(audio.gain);osc.start(now);osc.stop(now+1.6);osc.onended=()=>{osc.disconnect();g.disconnect();};}
 function command(name){if(!introDone)return;if(name==='wave')wave();else if(name==='meteor')meteorShower();else if(name==='tour')startTour();else if(name==='reset'){const p=pose(level.depth,selected);camera.position.copy(p.position);controls.target.copy(p.target);controls.update();}else if(name==='audio'){if(!audio)audio=setupAudio();if(!audio)return false;audioOn=!audioOn;audio.context.resume();audio.gain.gain.setTargetAtTime(audioOn?.025:0,audio.context.currentTime,.3);canvas.dataset.audio=String(audioOn);return audioOn;}else if(name.startsWith('model-')){const kind=name.slice(6);(selected?[selected]:level.nodes).forEach(n=>n.artifact.pulse(kind));if(kind==='wave')wave();canvas.dataset.modelAction=kind;}}
 function setParameter(id,key,value){const node=level?.nodes.find(n=>n.entry.id===id);node?.artifact.setParameter(key,value);canvas.dataset.parameter=key+':'+Number(value).toFixed(3);if(key==='rate')particleRate=.45+value*1.4;if(key==='spread')globalUniforms.uPull.value=value*.25;}
 function projectLabels(){for(const n of level?.nodes||[]){if(selected||transition){n.label.style.opacity='0';n.label.style.pointerEvents='none';continue;}projected.copy(n.position);projected.y+=level.depth===2?-3.6:1.25;projected.project(camera);const x=(projected.x*.5+.5)*innerWidth,y=(-projected.y*.5+.5)*innerHeight;const visible=projected.z<1&&x>38&&x<innerWidth-38&&y>110&&y<innerHeight-78;n.label.style.left=x+'px';n.label.style.top=y+'px';n.label.style.opacity=visible?'1':'0';n.label.style.pointerEvents=visible?'auto':'none';}}
 buildLevel([]);level.group.scale.setScalar(.01);resize();const initial=pose(0);camera.position.copy(initial.position).multiplyScalar(1.28);controls.target.copy(initial.target);controls.update();
 function tick(now){
  if(disposed)return;frame=requestAnimationFrame(tick);if(document.hidden)return;const dt=previous?Math.min(.05,(now-previous)/1000):.016;previous=now;elapsedTime+=dt*(reduced.matches?.2:1);globalUniforms.uTime.value=elapsedTime*particleRate;globalUniforms.uPull.value+=(pullTarget-globalUniforms.uPull.value)*Math.min(1,dt*4);
  if(waveAge<99){waveAge+=dt;globalUniforms.uWave.value=waveAge*16;if(waveAge>5)waveAge=99;}else globalUniforms.uWave.value=-30;
  for(const n of level.nodes)n.artifact.update(dt,elapsedTime);cosmos.rotation.y=.14+Math.sin(elapsedTime*.018)*.035;background.rotation.y=elapsedTime*.0007;core.rotation.y=elapsedTime*.03;
  if(!introDone&&introStart!==null){const elapsed=performance.now()-introStart,t=Math.min(1,elapsed/5000);globalUniforms.uReveal.value=.08+.92*smooth(Math.min(1,t*1.4));const p=pose(0);camera.position.copy(p.position).multiplyScalar(1+.28*(1-smooth(t)));camera.position.x=Math.sin(t*PI)*2.3*(reduced.matches?.2:1);controls.target.copy(p.target);camera.lookAt(controls.target);level.group.scale.setScalar(Math.max(.01,smooth(Math.max(0,(t-.4)/.55))));$('#intro-progress').textContent=Math.min(100,Math.floor(t*100))+'%';$('#intro').style.setProperty('--progress',t);$('#intro-caption').textContent=t<.35?'星尘汇聚，可能性开始诞生。':t<.72?'光，为每一种想象找到轨道。':'一个宇宙，等待你亲手探索。';if(elapsed>=4300&&!$('#intro').classList.contains('is-exiting')){$('#intro').classList.add('is-exiting');document.body.classList.add('intro-reveal');$('#intro').dataset.transitionAt=performance.now().toFixed(2);}if(elapsed>=5000){introDone=true;controls.enabled=true;globalUniforms.uReveal.value=1;level.group.scale.setScalar(1);$('#intro').dataset.elapsed=elapsed.toFixed(2);$('#intro').dataset.finishedAt=performance.now().toFixed(2);onIntroFinished?.();}}
  if(transition){const tr=transition,t=Math.min(1,(now-tr.started)/tr.duration);globalUniforms.uWarp.value=Math.sin(t*PI)*.65;if(t<.45){const a=ease(t/.45);camera.position.lerpVectors(tr.fromPosition,tr.viaTarget.clone().add(new THREE.Vector3(3,5,10)),a*.55);controls.target.lerpVectors(tr.fromTarget,tr.viaTarget,a*.5);level.group.scale.setScalar(1-a*.95);}else{if(!tr.built){buildLevel(tr.path);tr.built=true;const node=tr.path.length===3?level.nodes.find(n=>n.entry.id===tr.path[2].id):null;tr.toPose=pose(level.depth,node);tr.midPosition=camera.position.clone();tr.midTarget=controls.target.clone();}const a=smooth((t-.45)/.55);level.group.scale.setScalar(.05+.95*a);camera.position.lerpVectors(tr.midPosition,tr.toPose.position,a);controls.target.lerpVectors(tr.midTarget,tr.toPose.target,a);}camera.lookAt(controls.target);if(t>=1){const path=tr.path;transition=null;controls.enabled=true;globalUniforms.uWarp.value=0;globalUniforms.uDim.value=level.depth===0?1:level.depth===1?.22:.035;completeSelection(path);canvas.dataset.navigation='ready';document.body.classList.remove('navigating');}}
  else if(introDone)controls.update();
  for(let i=meteors.length-1;i>=0;i--){const m=meteors[i];m.age+=dt;if(m.age>=0){m.mesh.position.addScaledVector(m.velocity,dt);m.mesh.material.opacity=Math.max(0,(1-m.age/m.life)*.55);}if(m.age>m.life){scene.remove(m.mesh);m.mesh.geometry.dispose();m.mesh.material.dispose();meteors.splice(i,1);}}
  projectLabels();composer.render();if(introStart===null){introStart=performance.now();$('#intro').dataset.clockSource='three-first-render';$('#intro').dataset.duration='5000';$('#intro').dataset.startedAt=introStart.toFixed(2);canvas.dataset.engine='three.js r186';onReady?.();}
 }
 frame=requestAnimationFrame(tick);
 return{navigateTo,back,command,setParameter,refreshLabels,getState:()=>({depth:level.depth,path:level.path,selected:selected?.entry.id||null,seed,introDone}),capture:()=>{composer.render();return{dataUrl:canvas.toDataURL('image/png'),width:canvas.width,height:canvas.height};},dispose:()=>{disposed=true;cancelAnimationFrame(frame);clearTimeout(hold);clearTimeout(clickTimer);stopTour();events.forEach(off=>off());controls.dispose();disposeLevel();freeGroup(cosmos);background.geometry.dispose();background.material.dispose();for(const m of meteors){m.mesh.geometry.dispose();m.mesh.material.dispose();}glowTexture.dispose();environment.dispose();composer.passes.forEach(p=>p.dispose?.());composer.dispose();renderer.dispose();audio?.context.close();}};
}
